config/routes.rb
Tunr::Application.routes.draw do
  root :to => 'home#index'

  resources :users, :except => [:edit] do
    collection do
      get 'edit'
    end
  end

  resources :albums

  resources :artists

  resources :genres

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  image      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ActiveRecord::Base
  attr_accessible :name, :image
  has_many :songs
  has_many :artists, :through => :songs
  has_and_belongs_to_many :users
  validates :name, :presence => true, :length => { :minimum => 1 }
end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  image      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Artist < ActiveRecord::Base
  attr_accessible :name, :image
  has_many :songs
  has_many :albums, :through => :songs


end

app/models/genre.rb
# == Schema Information
#
# Table name: genres
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Genre < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :songs
end

app/models/mixtape.rb
# == Schema Information
#
# Table name: mixtapes
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Mixtape < ActiveRecord::Base
  attr_accessible :name, :user_id
  belongs_to :user
  has_and_belongs_to_many :songs
end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  image      :string(255)
#  filename   :string(255)
#  album_id   :integer
#  artist_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Song < ActiveRecord::Base
  attr_accessible :name, :image, :filename, :album_id, :artist_id
  belongs_to :album
  belongs_to :artist
  has_and_belongs_to_many :mixtapes
  has_and_belongs_to_many :genres
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  image           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  is_admin        :boolean          default(FALSE)
#  balance         :decimal(, )      default(0.0)
#

class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :name, :image, :password, :password_confirmation, :balance
  has_many :mixtapes
  has_and_belongs_to_many :albums

  validates :image, :presence => true
  validates :name, :uniqueness => true, :length => { :minimum => 2 }
  validates :balance, :numericality => { :greater_than_or_equal_to => 0 }
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :check_if_admin, :only => [:new, :create, :edit, :update]

  def index
    @albums = Album.order(:name)
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(params[:album])
    if @album.save
      redirect_to(albums_path)
    else
      @obj = @album
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :new
  end

  def update
    @album = Album.find(params[:id])
    if @album.update_attributes(params[:album])
      redirect_to(albums_path)
    else
      @obj = @album
      render :new
    end
  end

  private
  def check_if_admin
    redirect_to(root_path) if @auth.nil? || !@auth.is_admin?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authentication

  private
  def authentication
    @auth = User.find(session[:user_id]) if session[:user_id].present?
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_filter :check_if_admin, :only => [:new, :create, :edit, :update]

  def index
    @artists = Artist.order(:name)
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(params[:artist])
    if @artist.save
      redirect_to(artists_path)
    else
      @obj = @artist
      render :new
    end
  end

  def edit
    @artist = Artist.find(params[:id])
    render :new
  end

  def update
    @artist = artist.find(params[:id])
    if @artist.update_attributes(params[:artist])
      redirect_to(artists_path)
    else
      @obj = @artist
      render :new
    end
  end

  private
  def check_if_admin
    redirect_to(root_path) if @auth.nil? || !@auth.is_admin?
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_filter :check_if_admin, :only => [:new, :create, :edit, :update]

  def index
    @genres = Genre.order(:name)
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(params[:genre])
    if @genre.save
      redirect_to(genres_path)
    else
      @obj = @Genre
      render :new
    end
  end

  def edit
    @genre = Genre.find(params[:id])
    render :new
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update_attributes(params[:genre])
      redirect_to(genres_path)
    else
      @obj = @genre
      render :new
    end
  end

  private
  def check_if_admin
    redirect_to(root_path) if @auth.nil? || !@auth.is_admin?
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.where(:name => params[:username]).first
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to(root_path)
    else
      flash[:notice] = "Incorrect login. Please try again."
      redirect_to(login_path)
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to(root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_if_logged_in, :except => [:new, :create]
  before_filter :check_if_admin, :only => [:index, :destroy]

  def index
    @users = User.order(:name)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to(root_path)
    else
      @obj = @user
      render :new
    end
  end

  def edit
    @user = @auth
    render :new
  end

  def update
    @user = @auth
    if @user.update_attributes(params[:user])
      redirect_to(root_path)
    else
      @obj = @user
      render :new
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to(users_path)
  end

  private
  def check_if_logged_in
    redirect_to(root_path) if @auth.nil?
  end

  def check_if_admin
    redirect_to(root_path) if @auth.nil? || !@auth.is_admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_admin?
    @auth.present? && @auth.is_admin?
  end

  def intellinav
    links = ''
    links << "<li>#{link_to('List albums', albums_path)}</li>"
    links << "<li>#{link_to('List artists', artists_path)}</li>"
    links << "<li>#{link_to('List genres', genres_path)}</li>"
    if @auth.present?
      if @auth.is_admin
        links << "<li>#{link_to('Show Users', users_path)}</li>"
        links << "<li>#{link_to('Add album', new_album_path)}</li>"
      end
      links << "<li>#{link_to('Edit', edit_users_path)}</li>"
      links << "<li>"
      links << "#{link_to('Logout ' + @auth.name, login_path, :method => :delete, :confirm => 'Really?')}"
      links << " #{number_to_currency @auth.balance}"
      links << "</li>"
    else
      links << "<li>#{link_to('Create Account', new_user_path)}</li>"
      links << "<li>#{link_to('Login', login_path)}</li>"
    end

    links
  end
end

app/views/Genres/index.html.haml
%table#genres
  - @genres.each do |genre|
    %tr
      %td
        %span= genre.name
      %td
        %span= image_tag(genre.image)
      %td
        = link_to('Edit', edit_genre_path(genre), :class => 'button radius tiny') if is_admin?

app/views/Genres/new.html.haml
.row
  .small-5.columns
    = render(:partial => '/shared/errors')
    = form_for @genre do |f|
      = f.label :name
      = f.text_field :name, :autofocus => true
      = f.label :image
      = f.text_field :image
      = f.submit nil, :class => 'button radius'
  .small-7.columns

app/views/albums/index.html.haml
%table#albums
  - @albums.each do |album|
    %tr
      %td
        %span= album.name
      %td
        %span= album.artists.first.try(:name) || 'The Beatles'
      %td
        %span= image_tag(album.image)
      %td
        = link_to('Edit', edit_album_path(album), :class => 'button radius tiny') if is_admin?

app/views/albums/new.html.haml
.row
  .small-5.columns
    = render(:partial => '/shared/errors')
    = form_for @album do |f|
      = f.label :name
      = f.text_field :name, :autofocus => true
      = f.label :image
      = f.text_field :image
      = f.submit nil, :class => 'button radius'
  .small-7.columns

app/views/artists/index.html.haml
%table#artists
  - @artists.each do |artist|
    %tr
      %td
        %span= artist.name
      %td
        %span= image_tag(artist.image)
      %td
        = link_to('Edit', edit_artist_path(artist), :class => 'button radius tiny') if is_admin?

app/views/artists/new.html.haml
.row
  .small-5.columns
    = render(:partial => '/shared/errors')
    = form_for @artist do |f|
      = f.label :name
      = f.text_field :name, :autofocus => true
      = f.label :image
      = f.text_field :image
      = f.submit nil, :class => 'button radius'
  .small-7.columns

app/views/home/index.html.haml
Hello World

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav>
      <ul>
        <%== intellinav %>
      </ul>
    </nav>

    <% if flash[:notice].present? %>
      <div class="row">
        <div class="columns small-5 alert-box alert">
          <%= flash[:notice] %>
        </div>
        <div class="columns small-7"></div>
      </div>
    <% end %>


hello world


<%= yield %>


    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/session/new.html.haml
.row
  .small-5.columns
    = form_tag '/login' do
      = label_tag 'username', nil, :autofocus => true
      = text_field_tag 'username'
      = label_tag 'password'
      = password_field_tag 'password'
      = submit_tag 'Login to tunr', :class => 'button radius'
  .small-7.columns

app/views/shared/_errors.html.haml
- if @obj.present? && @obj.errors.any?
  %ol
    - @obj.errors.full_messages.each do |msg|
      %li
        %span.label.alert.radius= msg

app/views/users/index.html.haml
%table#users
  - @users.each do |user|
    %tr
      %td
        - if user.is_admin?
          %span.label.alert.radius= user.name
        - else
          %span.label.success.radius= user.name
      %td= image_tag(user.image)
      %td= number_to_currency(user.balance)
      %td= link_to('Delete', user, :method => :delete, :confirm => 'Really?', :class => 'button radius alert tiny') if user != @auth

app/views/users/new.html.haml
.row
  .small-5.columns
    = render(:partial => '/shared/errors')
    = form_for @user do |f|
      = f.label :name
      = f.text_field :name, :autofocus => true
      = f.label :image
      = f.text_field :image
      = f.label :balance
      = f.text_field :balance
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation
      = f.password_field :password_confirmation
      = f.submit nil, :class => 'button radius'
  .small-7.columns